name: Build assets

on:
  push:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: '8.1'
      - run: git submodule absorbgitdirs
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: pnpm
      - run: pnpm install
      - uses: actions/checkout@v3
        with:
          repository: lichess-org/ab
          ssh-key: ${{ secrets.id_rsa_ab }}
          ref: master
          path: ab
        continue-on-error: true
        id: ab
      - run: pnpm link "$GITHUB_WORKSPACE/ab"
        if: steps.ab.outcome == 'success'
      - run: ./ui/build --no-install -p
      - run: cd ui && pnpm run test && cd -
      - run: mkdir assets && mv public assets/ && cp LICENSE COPYING.md README.md assets/ && git log -n 1 --pretty=oneline > assets/commit.txt
      - run: mkdir assets/public/vendor/vosk
      - run: curl https://raw.githubusercontent.com/lichess-org/lifat/master/vosk/model-en-us-0.15.tar.gz > assets/public/vendor/vosk/model-en-us-0.15.tar.gz
      - run: curl https://raw.githubusercontent.com/lichess-org/lifat/master/vosk/model-fr-0.22.tar.gz > assets/public/vendor/vosk/model-fr-0.22.tar.gz
      - run: curl https://raw.githubusercontent.com/lichess-org/lifat/master/vosk/model-de-0.15.tar.gz > assets/public/vendor/vosk/model-de-0.15.tar.gz
      - run: cd assets && tar -cvpJf ../assets.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v3
        with:
          name: lila-assets
          path: assets.tar.xz
